<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(FaceOffxSupportedTargetFrameworks)</TargetFrameworks>
    <Description>ONNX models for FaceOFFx facial recognition library</Description>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\*.onnx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.0" />
  </ItemGroup>
</Project>
